name: Flipt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  config-verify:
    name: Verify Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.FLIPT_BOT_APP_ID }}
          installation_id: ${{ secrets.FLIPT_BOT_INSTALLATION_ID }}
          private_key: ${{ secrets.FLIPT_BOT_PRIVATE_KEY_PEM }}

      - name: Verify Configuration
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ":crossed_flags: Distribution rollouts must be within the range 0 to 100.\nhttps://github.com/predictab-le/config/blob/4ca668e4057498386bccf15655385166ea7009af/services/prediction/features.yaml#L16-L17"
            });

            core.setFailed("Flipt configuration is invalid.");
 
