name: Flipt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  config-verify:
    name: Verify Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Verify Configuration
        run: echo "success"
 
